name: trackpense
description: "A Flutter project used to track your daily income and expenses"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0
  flutter: 3.35.1

dependencies:
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5
  flutter: {sdk: flutter}
  go_router: ^16.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.6.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700